{% set name = "napari-aicsimageio" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-aicsimageio-{{ version }}.tar.gz
  sha256: 20295120186fd98b2eb0f460844c44697eb981d17ab74d28229be7b9b118a482

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8
    - pytest-runner >=5.2
    - setuptools-scm
  run:
    - aicsimageio >=4.6.3
    - fsspec
    - napari >=0.4.13
    - psutil >=5.7.0
    - python >=3.8
    # plugins
    - bioformats_jar >=2020.5.27
    - mrc >=0.2.0
    - nd2 >=0.3.0
    - readlif >=0.6.4

test:
  imports:
    - napari_aicsimageio
    - napari_aicsimageio.core
  commands:
    - pip list
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-aicsimageio/
  summary: AICSImageIO for napari. Multiple file format reading directly into napari using pure Python.
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://github.com/AllenCellModeling/napari-aicsimageio

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - evamaxfield
    - tlambert03
